version: "3.8"

services:
  redis:
    container_name: redis
    image: redis
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: redis-server /etc/redis/redis.conf --appendonly yes