version: "2.2"

services:
  elasticsearch:
    image: elasticsearch:8.4.3
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./persistence/elasticsearch/data:/usr/share/elasticsearch/data
      - ./persistence/elasticsearch/logs:/usr/share/elasticsearch/logs
      - ./persistence/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    environment:
      - TZ="Asia/Shanghai"
      - discovery.type=single-node
  kibana:
    image: kibana:8.4.3
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    environment:
      - TZ="Asia/Shanghai"
#      - I18N_LOCALE=zh-CN # 中文界面